"""set nullable=true for expected_product and received_product

Revision ID: a44fc5bc33ff
Revises: 1dec89b6a665
Create Date: 2026-08-11 17:45:25.526570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44fc5bc33ff'
down_revision: Union[str, Sequence[str], None] = '1dec89b6a665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_reviews', 'expected_product',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('refund_reviews', 'received_product',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_reviews', 'received_product',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('refund_reviews', 'expected_product',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
